### ISSUE TITLE
Error executing from flatpak

### ISSUE THREAD

**Issue by albfan** [Ryujinx/Opentk#6]
### Description

Running games fail under flatpak

```
00:00:00.975 |N| Application : Unhandled exception caught: System.InvalidCastException: Unable to cast object of type 'OpenTK.Platform.X11.X11WindowInfo' to type 'OpenTK.Platform.Linux.LinuxWindowInfo'.
   at OpenTK.Platform.Linux.LinuxFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GLWidget.Initialize()
   at OpenTK.GLWidget.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

### Repro steps

Build with:
https://github.com/flathub/flathub/pull/1778

app start correctly, but then running a game it fails with that error.

### Expected behavior

Same build from host works correctly, not sure why opentk select LinuxWindowInfo on flatpak

### Actual behavior

Riujinx GLWidget build X11WindowInfo but that factory tries to cast to LinuxWindowInfo

### Related information 

* flatpak freedesktop 19.08
* SDL or Native backend
* What version of OpenTK (1.0.5.12)
* What runtime (3,1.302)
* Workarounds (no)

**Comment by albfan** [comment]
Finally I was able to debug this.

Adding 

```
+            System.Diagnostics.Debug.Print("Running on X11 "+OpenTK.Configuration.RunningOnX11);
```

it returns:

```
Running on X11 False
```
Looking at check to detect if it is running on X11:

```
        private static bool DetectX11()
        {
           #if X11
           // Detect whether X is present.
           try { return OpenTK.Platform.X11.API.DefaultDisplay != IntPtr.Zero; }
           catch { return false; }
           #else 
           return false;
           #endif
        }
```

it is assigned on:

            DefaultDisplay = Functions.XOpenDisplay(IntPtr.Zero);

So I suppose something related with xopendisplay is failing.

I'm not sure how to get a dependency in debug mode, but my plan is to build opentk instead of the the package so I can build in debug mode and see all the traces (and add my own ones) to understand why this check is failing.

@emmauss So finally, the factory is failing to detect x11 so it fallsback to linux, hence the invalidcasting.

**Comment by albfan** [comment]
Adding this chunk of code:

```
using System.Runtime.InteropServices;
 
        [DllImport("libX11", EntryPoint = "XOpenDisplay")]
        private extern static IntPtr sys_XOpenDisplay(IntPtr display);

        internal static object Lock = new object();

        public static IntPtr XOpenDisplay(IntPtr display)
        {
            lock (Lock)
            {
                return sys_XOpenDisplay(display);
            }
        }
...
System.Diagnostics.Debug.Print("ptr display "+XOpenDisplay(IntPtr.Zero));
```

I get:

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libX11' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11: cannot open shared object file: No such file or directory
   at Ryujinx.Program.sys_XOpenDisplay(IntPtr display)
   at Ryujinx.Program.XOpenDisplay(IntPtr display) in /run/build/ryujinx/Ryujinx/Program.cs:line 33
   at Ryujinx.Program.Main(String[] args) in /run/build/ryujinx/Ryujinx/Program.cs:line 73
```

Of course a sandbox app do not have access to libX11, so this needs a patched opentk.

For that #4 needs to be reopen as right now I cannot build opentk on linux

**Comment by refi64** [comment]
Oh this...seems very familiar... IIRC .NET framework tries to load shared libraries assuming there are no suffixes after the `.so`, e.g. `libxyz.so.10` will not be picked up but `libxyz.so` is picked up... Does this work if you run the Flatpak on the SDK runtime (pass `-d`) or create a symlink `/app/lib/libxyz.so -> /usr/lib/.../libxyz.so.10`?

**Comment by albfan** [comment]
@refi64 Awesome, that's the problem! Now X11 is detected correctly
